# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: ls .
    - name: Accessing repository secret
      run: echo ${{ secrets.MYSECRETNAME }}
    - name: Use Node.js ${{ matrix.node-version }}
    
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Upload application artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: build
      
  deploy-to-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a single artifact        
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - run: ls .
      - run: echo Deploying to TEST environment
      
  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: deploy-to-test
    steps:
      - name: Download a single artifact        
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - run: ls .
      - run: echo Deploying to PROD environment
      
